apiVersion: v1
kind: Service
metadata:
  name: whisper-api
spec:
  selector:
    service: whisper-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000  # You can specify a port here
  type: NodePort
